package embeddedcontroller;

import static embeddedcontroller.EmbeddedController.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import javafx.embed.swing.JFXPanel;
import javax.swing.JFileChooser;
import model.EmailClient;
import model.FTPserver;
import model.MyTelnetClient;
import model.SystemDefinitions.*;
import model.TCPServer;

 
public class HomeScreen extends javax.swing.JFrame {

    // browser is implemented using JAVAFX
    public HomeScreen() {
        initComponents();
        DEBUG.log(Level.INFO,"Home Screen initialized");
        //3: Exit on Close 
        DEBUG.log(Level.INFO, "DefaultCloseOperation= {0}", getDefaultCloseOperation());
        Rearrage();
    }

public void Rearrage(){
    Dimension screenSize;
    // Get Screen Size
    Toolkit tk = Toolkit.getDefaultToolkit();
    screenSize=tk.getScreenSize();
    DEBUG.log(Level.INFO, "ScreeSize {0}",screenSize.toString());
    // Open Applciation Maximized
    this.setExtendedState(MAXIMIZED_BOTH);
    DEBUG.log(Level.INFO, "Home Bounds: {0}", getBounds().toString());
    
}   
    
// Add and Removing Devices 
public static void addDevice(DEVICE_TYPE type){


}
public static void removeDevice(){


}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        terminalPOPUpmenu = new javax.swing.JPopupMenu();
        FontSize = new javax.swing.JMenuItem();
        Clear = new javax.swing.JMenuItem();
        TCPServerAdvancedSettingsDialog = new javax.swing.JDialog();
        jPanel15 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tcpServerBind = new javax.swing.JComboBox<>();
        tcpServerTimeout = new javax.swing.JTextField();
        tcpServerReceiveBufferSize = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        save_tcpServerAdvSett = new javax.swing.JButton();
        cancel_tcpServerAdvSett = new javax.swing.JButton();
        mainUI = new javax.swing.JSplitPane();
        split_DeviceProp = new javax.swing.JPanel();
        horizontalSplit = new javax.swing.JSplitPane();
        tabs_Tools = new javax.swing.JPanel();
        hsTabs = new javax.swing.JTabbedPane();
        DeviceProperties = new javax.swing.JPanel();
        DeviceControls = new javax.swing.JPanel();
        myFTPclient = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 20), new java.awt.Dimension(20, 20), new java.awt.Dimension(20, 20));
        FTPConnectionControl = new javax.swing.JPanel();
        lable_serverIP = new javax.swing.JLabel();
        ftp_serverIP = new javax.swing.JTextField();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        lable_port = new javax.swing.JLabel();
        ftp_port = new javax.swing.JTextField();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        lable_username = new javax.swing.JLabel();
        ftp_userName = new javax.swing.JTextField();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        lable_password = new javax.swing.JLabel();
        ftp_password = new javax.swing.JPasswordField();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 20), new java.awt.Dimension(20, 20), new java.awt.Dimension(20, 20));
        ftp_connect = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 20), new java.awt.Dimension(20, 20), new java.awt.Dimension(20, 20));
        FTPserverLogPane = new javax.swing.JScrollPane();
        FTPserverCMDLog = new javax.swing.JTextArea();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 20), new java.awt.Dimension(20, 20), new java.awt.Dimension(20, 20));
        FileMangerPanel = new javax.swing.JPanel();
        Localside = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        browseLocalFile = new javax.swing.JToggleButton();
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        RefreshLocalFile = new javax.swing.JButton();
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        jPanel3 = new javax.swing.JPanel();
        lablePath = new javax.swing.JLabel();
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        localFilePath = new javax.swing.JTextField();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        jScrollPane4 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        TransferCotrolPanel = new javax.swing.JPanel();
        uploadClientToServer = new javax.swing.JButton();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 20), new java.awt.Dimension(20, 20), new java.awt.Dimension(20, 20));
        uploadServerToClient = new javax.swing.JButton();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        RemoteSide = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        jTextField2 = new javax.swing.JTextField();
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 20), new java.awt.Dimension(20, 20), new java.awt.Dimension(20, 20));
        FileUploadStatus = new javax.swing.JScrollPane();
        FilesStatus = new javax.swing.JTable();
        myFTPserver = new javax.swing.JPanel();
        FTPserverPropPanel = new javax.swing.JPanel();
        FTPservernameLable = new javax.swing.JLabel();
        FTPServerName = new javax.swing.JTextField();
        FTPPathLable = new javax.swing.JLabel();
        FTPServerPath = new javax.swing.JTextField();
        FTPportLabel = new javax.swing.JLabel();
        FTPServerPort = new javax.swing.JSpinner();
        BrowseFTPPath = new javax.swing.JToggleButton();
        FTPusernameLabel = new javax.swing.JLabel();
        FTPUserName = new javax.swing.JTextField();
        FTPpasswordLabel = new javax.swing.JLabel();
        FTPPassword = new javax.swing.JPasswordField();
        ShowFTPPassword = new javax.swing.JToggleButton();
        maxLogin_lable = new javax.swing.JLabel();
        FTPmaxLogin = new javax.swing.JSpinner();
        maxLoginperIP_lable = new javax.swing.JLabel();
        FTPMaxLoginPerIP = new javax.swing.JSpinner();
        StatusPanel = new javax.swing.JPanel();
        FTPServerStart = new javax.swing.JButton();
        FTPconnectionsLabel = new javax.swing.JLabel();
        FTPClientCount = new javax.swing.JTextField();
        FTPServerClientStatus = new javax.swing.JPanel();
        FTPClientTabel = new javax.swing.JScrollPane();
        FTPClientTableData = new javax.swing.JTable();
        PacketSender = new javax.swing.JPanel();
        TCPserver = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        tcpserverPortLable = new javax.swing.JLabel();
        tcpServerPort = new javax.swing.JSpinner();
        tcpserver_maxconnLable = new javax.swing.JLabel();
        tcpServerMaxConnections = new javax.swing.JSpinner();
        tcpServerAdvancedSettings = new javax.swing.JButton();
        startTCPServer = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TCPServerLog = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        clearTCPLog = new javax.swing.JToggleButton();
        UDPserver = new javax.swing.JPanel();
        TelnetTerminal = new javax.swing.JPanel();
        telnetTermainal = new javax.swing.JPanel();
        telnetServerResp = new javax.swing.JScrollPane();
        telentClientTerminal = new javax.swing.JTextArea();
        telnetCMDSendPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        telentCMD = new javax.swing.JTextField();
        filler20 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        telnetCMDSend = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        telnetEnableLocalEcho = new javax.swing.JCheckBox();
        filler19 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        telnetDeleteCMDAfterSend = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        telnetAddCR = new javax.swing.JCheckBox();
        telnetAddLF = new javax.swing.JCheckBox();
        telnetAddCRLF = new javax.swing.JCheckBox();
        telnetConnectionsPannel = new javax.swing.JPanel();
        telneClientConnect = new javax.swing.JButton();
        hostAddressLable = new javax.swing.JLabel();
        telnetHostAddress = new javax.swing.JTextField();
        telnetHostPortLable = new javax.swing.JLabel();
        telnetPort = new javax.swing.JSpinner();
        SerialTermainal = new javax.swing.JPanel();
        HTTPserver = new javax.swing.JPanel();
        EmailClient = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        contactInfopanel = new javax.swing.JPanel();
        mail_nameLabel = new javax.swing.JLabel();
        mail_emailLable = new javax.swing.JLabel();
        mail_phoneLable = new javax.swing.JLabel();
        email_userName = new javax.swing.JTextField();
        email_userEmail = new javax.swing.JTextField();
        email_userPhone = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        email_userMessage = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        email_send = new javax.swing.JButton();
        tabs_Logs = new javax.swing.JPanel();
        Logs = new javax.swing.JTabbedPane();
        log_Output_panel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        split_DeviceList = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DeviceList = new javax.swing.JTree();
        Toolbar = new javax.swing.JMenuBar();
        ToolsMenu = new javax.swing.JMenu();
        item_packetSender = new javax.swing.JMenuItem();
        item_telnetClient = new javax.swing.JMenuItem();
        item_serialClient = new javax.swing.JMenuItem();
        DebugMenu = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        SetupMenu = new javax.swing.JMenu();
        item_tcpServer = new javax.swing.JMenuItem();
        item_tcpClient = new javax.swing.JMenuItem();
        item_udpServer = new javax.swing.JMenuItem();
        item_udpClient = new javax.swing.JMenuItem();

        FontSize.setText("Font Size");
        terminalPOPUpmenu.add(FontSize);

        Clear.setText("Clear");
        terminalPOPUpmenu.add(Clear);

        TCPServerAdvancedSettingsDialog.setTitle("TCP Server Advanced Settings");
        TCPServerAdvancedSettingsDialog.setAlwaysOnTop(true);

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("TCP Server Advanced Settings"));

        jLabel1.setText("Receive Buffer Size");

        jLabel3.setText("Time Out (milli Sec)");

        jLabel4.setText("Bind");

        tcpServerTimeout.setText("0");
        tcpServerTimeout.setToolTipText("The timeout must be > 0. A timeout of zero is interpreted as an infinite timeout.");

        tcpServerReceiveBufferSize.setToolTipText("The value of BUFFER SIZE is used both to set the size of the internal socket receive buffer, and to set the size of the TCP receive window that is advertized to the remote peer");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tcpServerBind, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcpServerTimeout, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcpServerReceiveBufferSize, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tcpServerReceiveBufferSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tcpServerBind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tcpServerTimeout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TCPServerAdvancedSettingsDialog.getContentPane().add(jPanel15, java.awt.BorderLayout.CENTER);

        save_tcpServerAdvSett.setText("Save");
        save_tcpServerAdvSett.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_tcpServerAdvSettActionPerformed(evt);
            }
        });

        cancel_tcpServerAdvSett.setText("Cancel");
        cancel_tcpServerAdvSett.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_tcpServerAdvSettActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(390, Short.MAX_VALUE)
                .addComponent(cancel_tcpServerAdvSett)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(save_tcpServerAdvSett)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_tcpServerAdvSett)
                    .addComponent(cancel_tcpServerAdvSett))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        TCPServerAdvancedSettingsDialog.getContentPane().add(jPanel16, java.awt.BorderLayout.PAGE_END);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Embedded Controller");

        mainUI.setDividerSize(3);
        mainUI.setResizeWeight(0.4);

        split_DeviceProp.setLayout(new java.awt.BorderLayout(10, 0));

        horizontalSplit.setDividerSize(4);
        horizontalSplit.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        horizontalSplit.setResizeWeight(0.7);
        horizontalSplit.setToolTipText("");

        tabs_Tools.setLayout(new java.awt.BorderLayout());

        hsTabs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        hsTabs.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        javax.swing.GroupLayout DevicePropertiesLayout = new javax.swing.GroupLayout(DeviceProperties);
        DeviceProperties.setLayout(DevicePropertiesLayout);
        DevicePropertiesLayout.setHorizontalGroup(
            DevicePropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );
        DevicePropertiesLayout.setVerticalGroup(
            DevicePropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );

        hsTabs.addTab("Details", DeviceProperties);

        javax.swing.GroupLayout DeviceControlsLayout = new javax.swing.GroupLayout(DeviceControls);
        DeviceControls.setLayout(DeviceControlsLayout);
        DeviceControlsLayout.setHorizontalGroup(
            DeviceControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );
        DeviceControlsLayout.setVerticalGroup(
            DeviceControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );

        hsTabs.addTab("Controls", DeviceControls);

        myFTPclient.setMaximumSize(new java.awt.Dimension(300, 200));
        myFTPclient.setLayout(new javax.swing.BoxLayout(myFTPclient, javax.swing.BoxLayout.Y_AXIS));
        myFTPclient.add(filler4);

        FTPConnectionControl.setLayout(new javax.swing.BoxLayout(FTPConnectionControl, javax.swing.BoxLayout.LINE_AXIS));

        lable_serverIP.setText("Server IP");
        FTPConnectionControl.add(lable_serverIP);

        ftp_serverIP.setText("IP");
        FTPConnectionControl.add(ftp_serverIP);
        FTPConnectionControl.add(filler6);

        lable_port.setText("Port");
        FTPConnectionControl.add(lable_port);
        FTPConnectionControl.add(ftp_port);
        FTPConnectionControl.add(filler7);

        lable_username.setText("Username");
        FTPConnectionControl.add(lable_username);

        ftp_userName.setText("USERNAME");
        FTPConnectionControl.add(ftp_userName);
        FTPConnectionControl.add(filler8);

        lable_password.setText("Password");
        FTPConnectionControl.add(lable_password);

        ftp_password.setText("jPasswordField1");
        FTPConnectionControl.add(ftp_password);
        FTPConnectionControl.add(filler9);

        ftp_connect.setText("Connect");
        FTPConnectionControl.add(ftp_connect);

        myFTPclient.add(FTPConnectionControl);
        myFTPclient.add(filler1);

        FTPserverLogPane.setMinimumSize(new java.awt.Dimension(23, 75));

        FTPserverCMDLog.setColumns(20);
        FTPserverCMDLog.setRows(5);
        FTPserverCMDLog.setPreferredSize(new java.awt.Dimension(164, 110));
        FTPserverLogPane.setViewportView(FTPserverCMDLog);

        myFTPclient.add(FTPserverLogPane);
        myFTPclient.add(filler2);

        FileMangerPanel.setLayout(new javax.swing.BoxLayout(FileMangerPanel, javax.swing.BoxLayout.LINE_AXIS));

        Localside.setBorder(javax.swing.BorderFactory.createTitledBorder("Local"));
        Localside.setLayout(new javax.swing.BoxLayout(Localside, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setAlignmentX(1.0F);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        browseLocalFile.setText("Bowse");
        jPanel2.add(browseLocalFile);
        jPanel2.add(filler15);

        RefreshLocalFile.setText("Refresh");
        jPanel2.add(RefreshLocalFile);

        Localside.add(jPanel2);
        Localside.add(filler16);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        lablePath.setText("Path");
        jPanel3.add(lablePath);
        jPanel3.add(filler14);

        localFilePath.setText("jTextField1");
        jPanel3.add(localFilePath);

        Localside.add(jPanel3);
        Localside.add(filler13);

        jScrollPane4.setViewportView(jTree2);

        Localside.add(jScrollPane4);

        FileMangerPanel.add(Localside);
        FileMangerPanel.add(filler11);

        TransferCotrolPanel.setLayout(new javax.swing.BoxLayout(TransferCotrolPanel, javax.swing.BoxLayout.Y_AXIS));

        uploadClientToServer.setText("=>");
        TransferCotrolPanel.add(uploadClientToServer);
        TransferCotrolPanel.add(filler12);

        uploadServerToClient.setText("<=");
        TransferCotrolPanel.add(uploadServerToClient);

        FileMangerPanel.add(TransferCotrolPanel);
        FileMangerPanel.add(filler10);

        RemoteSide.setBorder(javax.swing.BorderFactory.createTitledBorder("Remote"));
        RemoteSide.setLayout(new javax.swing.BoxLayout(RemoteSide, javax.swing.BoxLayout.Y_AXIS));

        jButton2.setText("Refresh");
        jPanel4.add(jButton2);

        RemoteSide.add(jPanel4);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Path");
        jPanel5.add(jLabel2);
        jPanel5.add(filler18);

        jTextField2.setText("jTextField1");
        jPanel5.add(jTextField2);

        RemoteSide.add(jPanel5);
        RemoteSide.add(filler17);

        jScrollPane1.setViewportView(jTree1);

        RemoteSide.add(jScrollPane1);

        FileMangerPanel.add(RemoteSide);

        myFTPclient.add(FileMangerPanel);
        myFTPclient.add(filler3);

        FilesStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "File Name", "Local Path", "Direction", "Remote Path", "Status"
            }
        ));
        FileUploadStatus.setViewportView(FilesStatus);

        myFTPclient.add(FileUploadStatus);

        hsTabs.addTab("FTP Client", myFTPclient);

        FTPserverPropPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Server Config"));

        FTPservernameLable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        FTPservernameLable.setText("Server Name");

        FTPServerName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        FTPServerName.setText("MyFTPServer");

        FTPPathLable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        FTPPathLable.setText("Path");

        FTPServerPath.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        FTPportLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        FTPportLabel.setText("Port");

        FTPServerPort.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        FTPServerPort.setModel(new javax.swing.SpinnerNumberModel(21, 0, 65535, 1));

        BrowseFTPPath.setText("Browse");
        BrowseFTPPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseFTPPathActionPerformed(evt);
            }
        });

        FTPusernameLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        FTPusernameLabel.setText("Username");

        FTPUserName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        FTPUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FTPUserName.setText("admin");

        FTPpasswordLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        FTPpasswordLabel.setText("Password");

        FTPPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FTPPassword.setText("pass");

        ShowFTPPassword.setText("Show");

        maxLogin_lable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        maxLogin_lable.setText("Max Login ");

        FTPmaxLogin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        FTPmaxLogin.setModel(new javax.swing.SpinnerNumberModel(10, 1, 100, 1));

        maxLoginperIP_lable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        maxLoginperIP_lable.setText("Max Login/IP ");

        FTPMaxLoginPerIP.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        FTPMaxLoginPerIP.setModel(new javax.swing.SpinnerNumberModel(2, 1, 50, 1));

        javax.swing.GroupLayout FTPserverPropPanelLayout = new javax.swing.GroupLayout(FTPserverPropPanel);
        FTPserverPropPanel.setLayout(FTPserverPropPanelLayout);
        FTPserverPropPanelLayout.setHorizontalGroup(
            FTPserverPropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FTPserverPropPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(FTPserverPropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FTPpasswordLabel)
                    .addComponent(FTPportLabel)
                    .addComponent(FTPPathLable)
                    .addComponent(FTPservernameLable)
                    .addComponent(FTPusernameLabel)
                    .addComponent(maxLogin_lable)
                    .addComponent(maxLoginperIP_lable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FTPserverPropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FTPServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FTPserverPropPanelLayout.createSequentialGroup()
                        .addGroup(FTPserverPropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(FTPPassword)
                            .addComponent(FTPUserName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FTPServerPath, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FTPServerName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FTPserverPropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BrowseFTPPath)
                            .addComponent(ShowFTPPassword, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(FTPmaxLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FTPMaxLoginPerIP, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FTPserverPropPanelLayout.setVerticalGroup(
            FTPserverPropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FTPserverPropPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(FTPserverPropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FTPservernameLable)
                    .addComponent(FTPServerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FTPserverPropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FTPPathLable)
                    .addComponent(FTPServerPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BrowseFTPPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FTPserverPropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FTPportLabel)
                    .addComponent(FTPServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FTPserverPropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FTPusernameLabel)
                    .addComponent(FTPUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FTPserverPropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FTPpasswordLabel)
                    .addComponent(FTPPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowFTPPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FTPserverPropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxLogin_lable)
                    .addComponent(FTPmaxLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FTPserverPropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxLoginperIP_lable)
                    .addComponent(FTPMaxLoginPerIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        FTPServerStart.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        FTPServerStart.setText("Start");
        FTPServerStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTPServerStartActionPerformed(evt);
            }
        });

        FTPconnectionsLabel.setText("Connections:");

        FTPClientCount.setEditable(false);
        FTPClientCount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        FTPClientCount.setForeground(new java.awt.Color(0, 0, 255));
        FTPClientCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FTPClientCount.setText("0");

        javax.swing.GroupLayout StatusPanelLayout = new javax.swing.GroupLayout(StatusPanel);
        StatusPanel.setLayout(StatusPanelLayout);
        StatusPanelLayout.setHorizontalGroup(
            StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatusPanelLayout.createSequentialGroup()
                        .addComponent(FTPconnectionsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FTPClientCount, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(FTPServerStart, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        StatusPanelLayout.setVerticalGroup(
            StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(FTPServerStart, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(FTPClientCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FTPconnectionsLabel))
                .addGap(37, 37, 37))
        );

        FTPServerClientStatus.setBorder(javax.swing.BorderFactory.createTitledBorder("Client Status"));

        FTPClientTableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "IP", "User", "LoginTime", "Status", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FTPClientTabel.setViewportView(FTPClientTableData);

        javax.swing.GroupLayout FTPServerClientStatusLayout = new javax.swing.GroupLayout(FTPServerClientStatus);
        FTPServerClientStatus.setLayout(FTPServerClientStatusLayout);
        FTPServerClientStatusLayout.setHorizontalGroup(
            FTPServerClientStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FTPClientTabel)
        );
        FTPServerClientStatusLayout.setVerticalGroup(
            FTPServerClientStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FTPClientTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout myFTPserverLayout = new javax.swing.GroupLayout(myFTPserver);
        myFTPserver.setLayout(myFTPserverLayout);
        myFTPserverLayout.setHorizontalGroup(
            myFTPserverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myFTPserverLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(myFTPserverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FTPServerClientStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(myFTPserverLayout.createSequentialGroup()
                        .addComponent(FTPserverPropPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(StatusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        myFTPserverLayout.setVerticalGroup(
            myFTPserverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myFTPserverLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(myFTPserverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FTPserverPropPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StatusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FTPServerClientStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hsTabs.addTab("FTP Server", myFTPserver);

        javax.swing.GroupLayout PacketSenderLayout = new javax.swing.GroupLayout(PacketSender);
        PacketSender.setLayout(PacketSenderLayout);
        PacketSenderLayout.setHorizontalGroup(
            PacketSenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );
        PacketSenderLayout.setVerticalGroup(
            PacketSenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );

        hsTabs.addTab("Packet Sender ", PacketSender);

        TCPserver.setLayout(new java.awt.BorderLayout());

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("TCP Server"));

        tcpserverPortLable.setText("Port");

        tcpserver_maxconnLable.setText("Max Connections");

        tcpServerAdvancedSettings.setText("Advanced Settings");
        tcpServerAdvancedSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcpServerAdvancedSettingsActionPerformed(evt);
            }
        });

        startTCPServer.setText("Start");
        startTCPServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTCPServerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tcpserverPortLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tcpServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tcpserver_maxconnLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tcpServerMaxConnections, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tcpServerAdvancedSettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(startTCPServer, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(startTCPServer, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(tcpServerPort, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tcpserver_maxconnLable, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tcpserverPortLable, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcpServerMaxConnections, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tcpServerAdvancedSettings, javax.swing.GroupLayout.Alignment.CENTER))
                .addContainerGap())
        );

        TCPserver.add(jPanel12, java.awt.BorderLayout.PAGE_START);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Log"));
        jPanel13.setLayout(new java.awt.BorderLayout());

        TCPServerLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Time", "From IP", "To IP", "To Port", "Method", "Error", "ASCII", "Hex"
            }
        ));
        jScrollPane6.setViewportView(TCPServerLog);

        jPanel13.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        TCPserver.add(jPanel13, java.awt.BorderLayout.CENTER);

        clearTCPLog.setText("Clear");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(clearTCPLog))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearTCPLog, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TCPserver.add(jPanel14, java.awt.BorderLayout.PAGE_END);

        hsTabs.addTab("TCP Server", TCPserver);

        javax.swing.GroupLayout UDPserverLayout = new javax.swing.GroupLayout(UDPserver);
        UDPserver.setLayout(UDPserverLayout);
        UDPserverLayout.setHorizontalGroup(
            UDPserverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );
        UDPserverLayout.setVerticalGroup(
            UDPserverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );

        hsTabs.addTab("UDP Server", UDPserver);

        TelnetTerminal.setLayout(new java.awt.BorderLayout());

        telnetTermainal.setLayout(new java.awt.BorderLayout());

        telentClientTerminal.setEditable(false);
        telentClientTerminal.setBackground(new java.awt.Color(0, 0, 0));
        telentClientTerminal.setColumns(20);
        telentClientTerminal.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        telentClientTerminal.setForeground(new java.awt.Color(255, 255, 255));
        telentClientTerminal.setRows(5);
        telnetServerResp.setViewportView(telentClientTerminal);

        telnetTermainal.add(telnetServerResp, java.awt.BorderLayout.CENTER);

        telnetCMDSendPanel.setLayout(new javax.swing.BoxLayout(telnetCMDSendPanel, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setMinimumSize(new java.awt.Dimension(100, 23));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.X_AXIS));

        telentCMD.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        telentCMD.setMinimumSize(new java.awt.Dimension(100, 23));
        telentCMD.setPreferredSize(new java.awt.Dimension(100, 23));
        telentCMD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                telentCMDKeyReleased(evt);
            }
        });
        jPanel7.add(telentCMD);
        jPanel7.add(filler20);

        telnetCMDSend.setText("Send");
        telnetCMDSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telnetCMDSendActionPerformed(evt);
            }
        });
        jPanel7.add(telnetCMDSend);

        jPanel1.add(jPanel7);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        telnetEnableLocalEcho.setText("Local Echo");
        jPanel8.add(telnetEnableLocalEcho);
        jPanel8.add(filler19);

        telnetDeleteCMDAfterSend.setSelected(true);
        telnetDeleteCMDAfterSend.setText("Delete command after send");
        jPanel8.add(telnetDeleteCMDAfterSend);

        jPanel1.add(jPanel8);

        telnetCMDSendPanel.add(jPanel1);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        telnetAddCR.setText("CR");
        telnetAddCR.setToolTipText("Carriage Return");
        jPanel6.add(telnetAddCR);

        telnetAddLF.setText("LF");
        telnetAddLF.setToolTipText("Line Feed");
        jPanel6.add(telnetAddLF);

        telnetAddCRLF.setSelected(true);
        telnetAddCRLF.setText("CR+LF");
        telnetAddCRLF.setToolTipText("Carriage Return + Line Feed");
        jPanel6.add(telnetAddCRLF);

        telnetCMDSendPanel.add(jPanel6);

        telnetTermainal.add(telnetCMDSendPanel, java.awt.BorderLayout.PAGE_END);

        TelnetTerminal.add(telnetTermainal, java.awt.BorderLayout.CENTER);

        telnetConnectionsPannel.setBorder(javax.swing.BorderFactory.createTitledBorder("Telnet Server"));

        telneClientConnect.setText("Connect");
        telneClientConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telneClientConnectActionPerformed(evt);
            }
        });

        hostAddressLable.setText("Host Address");

        telnetHostPortLable.setText("Port");

        telnetPort.setModel(new javax.swing.SpinnerNumberModel(23, 1, 65535, 1));
        telnetPort.setToolTipText("Telnet Server Port");
        telnetPort.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        telnetPort.setEditor(new javax.swing.JSpinner.NumberEditor(telnetPort, "####"));

        javax.swing.GroupLayout telnetConnectionsPannelLayout = new javax.swing.GroupLayout(telnetConnectionsPannel);
        telnetConnectionsPannel.setLayout(telnetConnectionsPannelLayout);
        telnetConnectionsPannelLayout.setHorizontalGroup(
            telnetConnectionsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telnetConnectionsPannelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(hostAddressLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telnetHostAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(telnetHostPortLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(telnetPort, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(telneClientConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        telnetConnectionsPannelLayout.setVerticalGroup(
            telnetConnectionsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telnetConnectionsPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telnetConnectionsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hostAddressLable)
                    .addComponent(telnetHostAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telnetHostPortLable, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telnetPort, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telneClientConnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TelnetTerminal.add(telnetConnectionsPannel, java.awt.BorderLayout.PAGE_START);

        hsTabs.addTab("Telnet Terminal", TelnetTerminal);

        javax.swing.GroupLayout SerialTermainalLayout = new javax.swing.GroupLayout(SerialTermainal);
        SerialTermainal.setLayout(SerialTermainalLayout);
        SerialTermainalLayout.setHorizontalGroup(
            SerialTermainalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );
        SerialTermainalLayout.setVerticalGroup(
            SerialTermainalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );

        hsTabs.addTab("Serial Termainal", SerialTermainal);

        javax.swing.GroupLayout HTTPserverLayout = new javax.swing.GroupLayout(HTTPserver);
        HTTPserver.setLayout(HTTPserverLayout);
        HTTPserverLayout.setHorizontalGroup(
            HTTPserverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );
        HTTPserverLayout.setVerticalGroup(
            HTTPserverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );

        hsTabs.addTab("HTTP Server", HTTPserver);

        EmailClient.setLayout(new javax.swing.BoxLayout(EmailClient, javax.swing.BoxLayout.LINE_AXIS));

        jPanel10.setLayout(new java.awt.BorderLayout());

        contactInfopanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact Info"));

        mail_nameLabel.setText("Name");

        mail_emailLable.setText("Email");

        mail_phoneLable.setText("Phone");

        javax.swing.GroupLayout contactInfopanelLayout = new javax.swing.GroupLayout(contactInfopanel);
        contactInfopanel.setLayout(contactInfopanelLayout);
        contactInfopanelLayout.setHorizontalGroup(
            contactInfopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contactInfopanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(contactInfopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mail_nameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mail_phoneLable, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mail_emailLable, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(contactInfopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email_userName, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email_userEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email_userPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(223, 223, 223))
        );
        contactInfopanelLayout.setVerticalGroup(
            contactInfopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactInfopanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contactInfopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mail_nameLabel)
                    .addComponent(email_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(contactInfopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mail_emailLable)
                    .addComponent(email_userEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(contactInfopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mail_phoneLable)
                    .addComponent(email_userPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contactInfopanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contactInfopanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel10.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jScrollPane5.setBorder(javax.swing.BorderFactory.createTitledBorder("Message"));

        email_userMessage.setColumns(20);
        email_userMessage.setRows(5);
        jScrollPane5.setViewportView(email_userMessage);

        jPanel10.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        email_send.setText("Send");
        email_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_sendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(569, Short.MAX_VALUE)
                .addComponent(email_send, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(email_send, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        jPanel10.add(jPanel11, java.awt.BorderLayout.PAGE_END);

        EmailClient.add(jPanel10);

        hsTabs.addTab("Support", EmailClient);

        tabs_Tools.add(hsTabs, java.awt.BorderLayout.CENTER);

        horizontalSplit.setLeftComponent(tabs_Tools);

        tabs_Logs.setMaximumSize(new java.awt.Dimension(2147483647, 25));
        tabs_Logs.setPreferredSize(new java.awt.Dimension(171, 25));
        tabs_Logs.setLayout(new java.awt.BorderLayout());

        log_Output_panel.setLayout(new java.awt.BorderLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        log_Output_panel.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        Logs.addTab("Output", log_Output_panel);

        tabs_Logs.add(Logs, java.awt.BorderLayout.CENTER);

        horizontalSplit.setRightComponent(tabs_Logs);

        split_DeviceProp.add(horizontalSplit, java.awt.BorderLayout.CENTER);

        mainUI.setRightComponent(split_DeviceProp);

        split_DeviceList.setLayout(new java.awt.BorderLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("IP Devices");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("CNT-IP-264");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("IP:192.168.123.1");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Name: FHD Device Finder");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Location: Hall Research");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("VSA-UI-TS");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("IP:192.168.123.2l");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Name: VSA Controller");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Location: Hall Research");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("CNT-IP-2");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("IP:192.168.123.3");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Name: Room Controller");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Location: Hall Research");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Serial Devices");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("HSM-88-4K");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Com Port:1");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Baud:15000");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("SSW-HD-4");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Com Port:2");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Baud:15200");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        DeviceList.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(DeviceList);

        split_DeviceList.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        mainUI.setLeftComponent(split_DeviceList);

        getContentPane().add(mainUI, java.awt.BorderLayout.CENTER);

        ToolsMenu.setText("Tools");

        item_packetSender.setText("Packet Sender");
        item_packetSender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_packetSenderActionPerformed(evt);
            }
        });
        ToolsMenu.add(item_packetSender);

        item_telnetClient.setText("Telnet Terminal");
        item_telnetClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_telnetClientActionPerformed(evt);
            }
        });
        ToolsMenu.add(item_telnetClient);

        item_serialClient.setText("Serial Terminal");
        ToolsMenu.add(item_serialClient);

        Toolbar.add(ToolsMenu);

        DebugMenu.setText("Debug");

        jMenuItem4.setText("Generate Debug Report");
        DebugMenu.add(jMenuItem4);

        Toolbar.add(DebugMenu);

        SetupMenu.setText("Setup");

        item_tcpServer.setText("TCP Server");
        SetupMenu.add(item_tcpServer);

        item_tcpClient.setText("TCP Client");
        SetupMenu.add(item_tcpClient);

        item_udpServer.setText("UDP Server");
        SetupMenu.add(item_udpServer);

        item_udpClient.setText("UDP Client");
        SetupMenu.add(item_udpClient);

        Toolbar.add(SetupMenu);

        setJMenuBar(Toolbar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void item_packetSenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_packetSenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_packetSenderActionPerformed

    private void item_telnetClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_telnetClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_telnetClientActionPerformed

    private void FTPServerStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTPServerStartActionPerformed
        // Start the FTP Server 
        DEBUG.log(Level.INFO,"FTPServer : {0}",evt.getActionCommand());
        if("Start".equals(evt.getActionCommand())){
            String name ="";
            String path = ""; 
            int port =-1;
            String userName = "";
            String passWord ="";
            name = FTPServerName.getText();
            path = FTPServerPath.getText();
            port = (int)FTPServerPort.getValue();
            DEBUG.log(Level.INFO,"FTPServer : {0}","Starting the server in port = "+port);
    
            userName = FTPUserName.getText();
            passWord = new String(FTPPassword.getPassword());
            
            // validate all the pram
            DEBUG.log(Level.INFO,"FTPServer : {0}","Name = "+name+" path= "+path+" Username= "+userName+" Pass= "+passWord);
            
            //Start the server
            EmbeddedController.myFTPServer = new FTPserver(name, port, path, userName, passWord);

            FTPServerStart.setText("Stop");

        }else{
        DEBUG.log(Level.INFO,"FTPServer : {0}","Stopping the Server");
        FTPServerStart.setText("Start");
            EmbeddedController.myFTPServer.StopServer();
        }
    }//GEN-LAST:event_FTPServerStartActionPerformed

    private void BrowseFTPPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseFTPPathActionPerformed
        
        DEBUG.log(Level.INFO,"FTPServer : {0}","Choosing Directory");
        // open File chooser 
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("FTP Directory");
        // choose only directory
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false); 
        String path=""; 
        
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            // Get the directory
            path = chooser.getSelectedFile().getAbsolutePath();
            DEBUG.log(Level.INFO,"FTPServer : Dir Path {0}",path);
            FTPServerPath.setText(path);
               
        }else {
            DEBUG.log(Level.WARNING,"FTPServer : Dir Path = No Selection!");
        }
    }//GEN-LAST:event_BrowseFTPPathActionPerformed

    
    private void telneClientConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telneClientConnectActionPerformed
        
        if("Connect".equals(telneClientConnect.getActionCommand())){
            // validate server IP and Port
            
            String serverIp = telnetHostAddress.getText();
            int port = (int)telnetPort.getValue();
            myTelnetClient = new MyTelnetClient(serverIp,port);
            if(myTelnetClient.isConnected()){
                telneClientConnect.setText("Disconnect");
                
                // disable host address and port fields
                telnetHostAddress.setEnabled(false);
                telnetPort.setEnabled(false);
            }                    
        }else {
            if (myTelnetClient != null) {
                myTelnetClient.stop();               
            }
            telneClientConnect.setText("Connect");
             telnetHostAddress.setEnabled(true);
             telnetPort.setEnabled(true);
        }
    }//GEN-LAST:event_telneClientConnectActionPerformed

    private void telnetCMDSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telnetCMDSendActionPerformed
         if (myTelnetClient != null) {
            String cmd = telentCMD.getText();
            myTelnetClient.send(cmd);
            // if the server has echo feature you will automatically get the echo else
            if (telnetDeleteCMDAfterSend.isSelected()) {
                telentCMD.setText("");
            }
            if (telnetEnableLocalEcho.isSelected()) {
                telentClientTerminal.append(">" + cmd + "\r\n");
            }
        }
    }//GEN-LAST:event_telnetCMDSendActionPerformed

    private void telentCMDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telentCMDKeyReleased
        // send command when Enter is pressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           telnetCMDSend.doClick();     
        }
    }//GEN-LAST:event_telentCMDKeyReleased

    private void email_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_sendActionPerformed
               
           emailClient = new EmailClient();
           String subject = "Support For : "+email_userName.getText();
           String message = "User Info\r\n ---------- \r\n Name:"+
                                    email_userName.getText()+
                                    "\r\n Email: "+email_userEmail.getText()+
                                    "\r\n Phone: "+email_userPhone.getText()+
                                    "\r\n \r\n Message: \r\n ------------- \r\n"+ 
                                    email_userMessage.getText();
           emailClient.send(subject, message);       
    }//GEN-LAST:event_email_sendActionPerformed

    private void startTCPServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTCPServerActionPerformed
        // start TCP server
         int port = (int)tcpServerPort.getValue();
         int maxConn = (int)tcpServerMaxConnections.getValue();
         
         // validate the port
         myTCPServer = new TCPServer(port,maxConn);          
    }//GEN-LAST:event_startTCPServerActionPerformed

    private void tcpServerAdvancedSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcpServerAdvancedSettingsActionPerformed
        TCPServerAdvancedSettingsDialog.setVisible(true);
    }//GEN-LAST:event_tcpServerAdvancedSettingsActionPerformed

    private void cancel_tcpServerAdvSettActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_tcpServerAdvSettActionPerformed
         TCPServerAdvancedSettingsDialog.setVisible(false);
         
    }//GEN-LAST:event_cancel_tcpServerAdvSettActionPerformed

    private void save_tcpServerAdvSettActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_tcpServerAdvSettActionPerformed
        TCPServerAdvancedSettingsDialog.setVisible(false);
    }//GEN-LAST:event_save_tcpServerAdvSettActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BrowseFTPPath;
    private javax.swing.JMenuItem Clear;
    private javax.swing.JMenu DebugMenu;
    private javax.swing.JPanel DeviceControls;
    private javax.swing.JTree DeviceList;
    private javax.swing.JPanel DeviceProperties;
    private javax.swing.JPanel EmailClient;
    public javax.swing.JTextField FTPClientCount;
    private javax.swing.JScrollPane FTPClientTabel;
    public javax.swing.JTable FTPClientTableData;
    private javax.swing.JPanel FTPConnectionControl;
    private javax.swing.JSpinner FTPMaxLoginPerIP;
    private javax.swing.JPasswordField FTPPassword;
    private javax.swing.JLabel FTPPathLable;
    private javax.swing.JPanel FTPServerClientStatus;
    private javax.swing.JTextField FTPServerName;
    private javax.swing.JTextField FTPServerPath;
    private javax.swing.JSpinner FTPServerPort;
    private javax.swing.JButton FTPServerStart;
    private javax.swing.JTextField FTPUserName;
    private javax.swing.JLabel FTPconnectionsLabel;
    private javax.swing.JSpinner FTPmaxLogin;
    private javax.swing.JLabel FTPpasswordLabel;
    private javax.swing.JLabel FTPportLabel;
    private javax.swing.JTextArea FTPserverCMDLog;
    private javax.swing.JScrollPane FTPserverLogPane;
    private javax.swing.JPanel FTPserverPropPanel;
    private javax.swing.JLabel FTPservernameLable;
    private javax.swing.JLabel FTPusernameLabel;
    private javax.swing.JPanel FileMangerPanel;
    private javax.swing.JScrollPane FileUploadStatus;
    private javax.swing.JTable FilesStatus;
    private javax.swing.JMenuItem FontSize;
    private javax.swing.JPanel HTTPserver;
    private javax.swing.JPanel Localside;
    private javax.swing.JTabbedPane Logs;
    private javax.swing.JPanel PacketSender;
    private javax.swing.JButton RefreshLocalFile;
    private javax.swing.JPanel RemoteSide;
    private javax.swing.JPanel SerialTermainal;
    private javax.swing.JMenu SetupMenu;
    private javax.swing.JToggleButton ShowFTPPassword;
    private javax.swing.JPanel StatusPanel;
    private javax.swing.JDialog TCPServerAdvancedSettingsDialog;
    private javax.swing.JTable TCPServerLog;
    private javax.swing.JPanel TCPserver;
    private javax.swing.JPanel TelnetTerminal;
    private javax.swing.JMenuBar Toolbar;
    private javax.swing.JMenu ToolsMenu;
    private javax.swing.JPanel TransferCotrolPanel;
    private javax.swing.JPanel UDPserver;
    private javax.swing.JToggleButton browseLocalFile;
    private javax.swing.JButton cancel_tcpServerAdvSett;
    private javax.swing.JToggleButton clearTCPLog;
    private javax.swing.JPanel contactInfopanel;
    private javax.swing.JButton email_send;
    private javax.swing.JTextField email_userEmail;
    private javax.swing.JTextArea email_userMessage;
    private javax.swing.JTextField email_userName;
    private javax.swing.JTextField email_userPhone;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler18;
    private javax.swing.Box.Filler filler19;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler20;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton ftp_connect;
    private javax.swing.JPasswordField ftp_password;
    private javax.swing.JTextField ftp_port;
    private javax.swing.JTextField ftp_serverIP;
    private javax.swing.JTextField ftp_userName;
    private javax.swing.JSplitPane horizontalSplit;
    private javax.swing.JLabel hostAddressLable;
    private javax.swing.JTabbedPane hsTabs;
    private javax.swing.JMenuItem item_packetSender;
    private javax.swing.JMenuItem item_serialClient;
    private javax.swing.JMenuItem item_tcpClient;
    private javax.swing.JMenuItem item_tcpServer;
    private javax.swing.JMenuItem item_telnetClient;
    private javax.swing.JMenuItem item_udpClient;
    private javax.swing.JMenuItem item_udpServer;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTree jTree1;
    private javax.swing.JTree jTree2;
    private javax.swing.JLabel lablePath;
    private javax.swing.JLabel lable_password;
    private javax.swing.JLabel lable_port;
    private javax.swing.JLabel lable_serverIP;
    private javax.swing.JLabel lable_username;
    private javax.swing.JTextField localFilePath;
    private javax.swing.JPanel log_Output_panel;
    private javax.swing.JLabel mail_emailLable;
    private javax.swing.JLabel mail_nameLabel;
    private javax.swing.JLabel mail_phoneLable;
    private javax.swing.JSplitPane mainUI;
    private javax.swing.JLabel maxLogin_lable;
    private javax.swing.JLabel maxLoginperIP_lable;
    private javax.swing.JPanel myFTPclient;
    private javax.swing.JPanel myFTPserver;
    private javax.swing.JButton save_tcpServerAdvSett;
    private javax.swing.JPanel split_DeviceList;
    private javax.swing.JPanel split_DeviceProp;
    private javax.swing.JButton startTCPServer;
    private javax.swing.JPanel tabs_Logs;
    private javax.swing.JPanel tabs_Tools;
    private javax.swing.JButton tcpServerAdvancedSettings;
    private javax.swing.JComboBox<String> tcpServerBind;
    private javax.swing.JSpinner tcpServerMaxConnections;
    private javax.swing.JSpinner tcpServerPort;
    private javax.swing.JTextField tcpServerReceiveBufferSize;
    private javax.swing.JTextField tcpServerTimeout;
    private javax.swing.JLabel tcpserverPortLable;
    private javax.swing.JLabel tcpserver_maxconnLable;
    private javax.swing.JTextField telentCMD;
    public javax.swing.JTextArea telentClientTerminal;
    private javax.swing.JButton telneClientConnect;
    public javax.swing.JCheckBox telnetAddCR;
    public javax.swing.JCheckBox telnetAddCRLF;
    public javax.swing.JCheckBox telnetAddLF;
    private javax.swing.JButton telnetCMDSend;
    private javax.swing.JPanel telnetCMDSendPanel;
    private javax.swing.JPanel telnetConnectionsPannel;
    private javax.swing.JCheckBox telnetDeleteCMDAfterSend;
    private javax.swing.JCheckBox telnetEnableLocalEcho;
    private javax.swing.JTextField telnetHostAddress;
    private javax.swing.JLabel telnetHostPortLable;
    private javax.swing.JSpinner telnetPort;
    private javax.swing.JScrollPane telnetServerResp;
    private javax.swing.JPanel telnetTermainal;
    private javax.swing.JPopupMenu terminalPOPUpmenu;
    private javax.swing.JButton uploadClientToServer;
    private javax.swing.JButton uploadServerToClient;
    // End of variables declaration//GEN-END:variables
}
